FROM ubuntu:22.04
RUN apt-get update && apt-get install -y cmake python2 python3 python3-pip libseccomp-dev gcc g++ strace && pip3 install setuptools --upgrade && ln -sf /usr/bin/pip3 /usr/bin/pip && ln -sf /usr/bin/python3 /usr/bin/python
WORKDIR /src