name: C/C++ CI

on:
  push:
    branches: [ "ubuntu_2204" ]
  pull_request:
    branches: [ "ubuntu_2204" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: mkdir
      run: rm -rf build && mkdir build && cd build && cmake ..
    - name: make
      run: make
    - name: make install
      run: make install
